name: Update

# Triggered manually or on release creation
on:
  workflow_dispatch:
    inputs:
      increment:
        description: "Increment (major, minor, patch)"
        required: true
        default: "patch"
      force:
        description: "Force update (even if sdk is up to date)"
        required: false
        default: "false"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update:
    name: Update version and dependencies
    runs-on: macos-latest # required for pod info / update

    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo

      - uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "17"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Check if Flutter SDK requires update
        if: github.event.inputs.force != 'true'
        run: bash .github/scripts/check_before_update.sh

      - name: Update Flutter SDK
        run: bash .github/scripts/update.sh ${{ github.event.inputs.increment }}

      - name: Commit & Push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Update Dependencies and increment ${{ github.event.inputs.increment }} version"
          commit_user_name: ${{ secrets.AUTHOR_NAME }}
          commit_user_email: ${{ secrets.AUTHOR_EMAIL }}
          commit_author: ${{ secrets.AUTHOR_NAME }} <${{ secrets.AUTHOR_EMAIL }}>

      - name: Trigger Tag
        run: |
          curl --request POST \
              --url 'https://api.github.com/repos/didomi/flutter/actions/workflows/tag.yml/dispatches' \
              --header 'authorization: Bearer ${{ secrets.CUSTOM_GITHUB_TOKEN }}' \
              --data '{ "ref": "${{ github.ref }}" }'
